let obj={
  docstatus: 0,
  doctype: "Sales Invoice",
  name: "new-sales-invoice-bfbpkipkkt",
  __islocal: 1,
  __unsaved: 1,
  owner: "kunal.m@jcssglobal.com",
  naming_series: "SINV-KL-",
  e_waybill_status: "",
  company: "HATTI FOOD AND BEVERAGES PVT LTD",
  is_pos: 0,
  is_consolidated: 0,
  is_return: 0,
  update_outstanding_for_self: 1,
  update_billed_amount_in_sales_order: 0,
  update_billed_amount_in_delivery_note: 1,
  is_debit_note: 0,
  is_reverse_charge: 0,
  is_export_with_gst: 0,
  currency: "INR",
  selling_price_list: "Standard Selling",
  price_list_currency: "INR",
  ignore_pricing_rule: 0,
  update_stock: 1,
  use_company_roundoff_cost_center: 0,
  disable_rounded_total: 0,
  apply_discount_on: "Grand Total",
  is_cash_or_non_trade_discount: 0,
  pricing_rules: [],
  packed_items: [],
  timesheets: [],
  total_billing_amount: 0,
  payments: [],
  allocate_advances_automatically: 0,
  only_include_allocated_payments: 0,
  advances: [],
  write_off_outstanding_amount_automatically: 0,
  redeem_loyalty_points: 0,
  export_type: "Without Payment of Tax",
  ignore_default_payment_terms_template: 0,
  payment_schedule: [],
  party_account_currency: "INR",
  is_opening: "No",
  sales_team: [],
  letter_head: "HK-01",
  group_same_items: 0,
  invoice_copy: "Original for Recipient",
  reverse_charge: "N",
  mode_of_transport: "Road",
  lr_date: new Date().toISOString().split('T')[0],
  gst_vehicle_type: "Regular",
  reason_for_issuing_document: "",
  status: "Draft",
  einvoice_status: "",
  is_internal_customer: 0,
  is_discounted: 0,
  conversion_rate: 1,
  plc_conversion_rate: 1,
  total_billing_hours: 0,
  company_tax_id: "AADCH5732N",
  company_address: "HATTI FOOD AND BEVERAGES PVT LTD (KA)",
  company_gstin: "29AADCH5732N1Z4",
  company_address_display: "No.17/1, 1st Main Road, Mahalakshmi Layout<br>Bengaluru<br>\nKarnataka, State Code: 29<br>Postal Code: 560086<br>India<br>\nEmail: sadashiv@hattikaapi.in<br>GSTIN: 29AADCH5732N1Z4<br>",
  taxes_and_charges: "Output GST In-state - HFABPL",
  base_net_total: 528.2,
  net_total: 528.2,
  base_total: 528.2,
  total: 528.2,
  total_qty: 13,
  rounding_adjustment: -0.48,
  grand_total: 611.48,
  base_grand_total: 611.48,
  total_taxes_and_charges: 83.28,
  base_total_taxes_and_charges: 83.28,
  base_rounding_adjustment: -0.48,
  rounded_total: 611,
  base_rounded_total: 611,
  in_words: "",
  base_in_words: "",
  base_discount_amount: 0,
  total_advance: 0,
  write_off_amount: 0,
  paid_amount: 0,
  base_paid_amount: 0,
  change_amount: 0,
  base_change_amount: 0,
  outstanding_amount: 611,
  amount_eligible_for_commission: 0,
  total_commission: null,
  posting_date: new Date().toISOString().split('T')[0],
  posting_time: new Date().toTimeString().split(' ')[0],
  due_date: new Date().toISOString().split('T')[0],
  tax_id: "29AAECH3107Q1Z8",
  customer_name: "Hyggelig Co-Working Private Limited",
  loyalty_program: null,
  represents_company: null,
  customer: "CUST-2020-00443",
  debit_to: "Debtors - HFABPL",
  customer_address: "Hyggelig Co-Working Private Limited-Billing",
  billing_address_gstin: "29AAECH3107Q1Z8",
  gst_category: "Registered Regular",
  address_display: "(SparkPlug Coworks)No.42, 100 Feet Rd, Koramangala 4th Block,<br>Bengaluru<br>Bengaluru<br>\nKarnataka, State Code: 29<br>Postal Code: 560034<br>India<br>\nGSTIN: 29AAECH3107Q1Z8<br>",
  shipping_address_name: null,
  customer_gstin: null,
  shipping_address: null,
  tax_category: "In-State",
  place_of_supply: "29-Karnataka",
  contact_person: null,
  contact_display: null,
  contact_email: null,
  contact_mobile: null,
  customer_group: "VENDING",
  territory: "KARNATAKA",
  language: "en",
  payment_terms_template: null
}

module.exports = obj;