let test={
    "docstatus": 0,
    "doctype": "Sales Invoice",
    "name": "new-sales-invoice-bfbpkipkkt",
    "__islocal": 1,
    "__unsaved": 1,
    "owner": "kunal.m@jcssglobal.com",
    "naming_series": "SINV-KL-",
    "e_waybill_status": "",
    "company": "HATTI FOOD AND BEVERAGES PVT LTD",
    "is_pos": 0,
    "is_consolidated": 0,
    "is_return": 0,
    "update_outstanding_for_self": 1,
    "update_billed_amount_in_sales_order": 0,
    "update_billed_amount_in_delivery_note": 1,
    "is_debit_note": 0,
    "is_reverse_charge": 0,
    "is_export_with_gst": 0,
    "currency": "INR",
    "selling_price_list": "Standard Selling",
    "price_list_currency": "INR",
    "ignore_pricing_rule": 0,
    "update_stock": 1,
    "use_company_roundoff_cost_center": 0,
    "disable_rounded_total": 0,
    "apply_discount_on": "Grand Total",
    "is_cash_or_non_trade_discount": 0,
    "pricing_rules": [],
    "packed_items": [],
    "timesheets": [],
    "total_billing_amount": 0,
    "payments": [],
    "allocate_advances_automatically": 0,
    "only_include_allocated_payments": 0,
    "advances": [],
    "write_off_outstanding_amount_automatically": 0,
    "redeem_loyalty_points": 0,
    "export_type": "Without Payment of Tax",
    "ignore_default_payment_terms_template": 0,
    "payment_schedule": [],
    "party_account_currency": "INR",
    "is_opening": "No",
    "sales_team": [],
    "letter_head": "HK-01",
    "group_same_items": 0,
    "invoice_copy": "Original for Recipient",
    "reverse_charge": "N",
    "mode_of_transport": "Road",
    "lr_date": "2025-01-07",
    "gst_vehicle_type": "Regular",
    "reason_for_issuing_document": "",
    "status": "Draft",
    "einvoice_status": "",
    "is_internal_customer": 0,
    "is_discounted": 0,
    "conversion_rate": 1,
    "plc_conversion_rate": 1,
    "total_billing_hours": 0,
    "company_tax_id": "AADCH5732N",
    "company_address": "HATTI FOOD AND BEVERAGES PVT LTD (KA)",
    "company_gstin": "29AADCH5732N1Z4",
    "company_address_display": "No.17/1, 1st Main Road, Mahalakshmi Layout\u003Cbr\u003EBengaluru\u003Cbr\u003E\nKarnataka, State Code: 29\u003Cbr\u003EPostal Code: 560086\u003Cbr\u003EIndia\u003Cbr\u003E\nEmail: sadashiv@hattikaapi.in\u003Cbr\u003EGSTIN: 29AADCH5732N1Z4\u003Cbr\u003E",
    "taxes_and_charges": "Output GST In-state - HFABPL",
    "base_net_total": 5185.65,
    "net_total": 5185.65,
    "base_total": 5185.65,
    "total": 5185.65,
    "total_qty": 78,
    "rounding_adjustment": 0.07,
    "grand_total": 5369.93,
    "base_grand_total": 5185.65,
    "total_taxes_and_charges": 184.28,
    "base_total_taxes_and_charges": 184.28,
    "base_rounding_adjustment": 0.07,
    "rounded_total": 5370,
    "base_rounded_total": 5370,
    "in_words": "",
    "base_in_words": "",
    "base_discount_amount": 0,
    "total_advance": 0,
    "write_off_amount": 0,
    "paid_amount": 0,
    "base_paid_amount": 0,
    "change_amount": 0,
    "base_change_amount": 0,
    "outstanding_amount": 5370,
    "amount_eligible_for_commission": 0,
    "total_commission": null,
    "posting_date": "2025-01-07",
    "posting_time": "16:09:23",
    "due_date": "2025-01-07",
    "tax_id": "29AAECH3107Q1Z8",
    "customer_name": "Hyggelig Co-Working Private Limited",
    "loyalty_program": null,
    "represents_company": null,
    "customer": "CUST-2020-00443",
    "debit_to": "Debtors - HFABPL",
    "customer_address": "Hyggelig Co-Working Private Limited-Billing",
    "billing_address_gstin": "29AAECH3107Q1Z8",
    "gst_category": "Registered Regular",
    "address_display": "(SparkPlug Coworks)No.42, 100 Feet Rd, Koramangala 4th Block,\u003Cbr\u003EBengaluru\u003Cbr\u003EBengaluru\u003Cbr\u003E\nKarnataka, State Code: 29\u003Cbr\u003EPostal Code: 560034\u003Cbr\u003EIndia\u003Cbr\u003E\nGSTIN: 29AAECH3107Q1Z8\u003Cbr\u003E",
    "shipping_address_name": null,
    "customer_gstin": null,
    "shipping_address": null,
    "tax_category": "In-State",
    "place_of_supply": "29-Karnataka",
    "contact_person": null,
    "contact_display": null,
    "contact_email": null,
    "contact_mobile": null,
    "customer_group": "VENDING",
    "territory": "KARNATAKA",
    "language": "en",
    "payment_terms_template": null,
    "items": [
        {
            "__islocal": 1,
            "__unsaved": 1,
            "actual_batch_qty": 0,
            "actual_qty": 0,
            "allow_zero_valuation_rate": 0,
            "amount": 85.71,
            "base_amount": 85.71,
            "base_net_amount": 85.71,
            "base_net_rate": 85.71,
            "base_price_list_rate": 0,
            "base_rate": 85.71,
            "base_rate_with_margin": 0,
            "cess_amount": 0,
            "cess_non_advol_amount": 0,
            "cess_non_advol_rate": 0,
            "cess_rate": 0,
            "cgst_amount": 0,
            "cgst_rate": 0,
            "child_docname": "new-sales-invoice-item-uicnovjvho",
            "company_total_stock": 0,
            "conversion_factor": 0,
            "cost_center": "BRIGADE ROAD - HK",
            "delivered_by_supplier": 0,
            "delivered_qty": 0,
            "description": "Ginger Tea (medium)",
            "discount_account": "Discount Allowed - HFABPL",
            "discount_amount": 0,
            "discount_percentage": 0,
            "docstatus": 0,
            "doctype": "Sales Invoice Item",
            "enable_deferred_revenue": 0,
            "grant_commission": 0,
            "has_item_scanned": 0,
            "has_margin": false,
            "idx": 1,
            "igst_amount": 0,
            "igst_rate": 0,
            "income_account": "Sale of Products - Beverages and Food - HFABPL",
            "incoming_rate": 0,
            "is_fixed_asset": 0,
            "is_free_item": 0,
            "item_code": "Ginger Tea (medium)",
            "item_group": "HOT BEVERAGES (GST 5%)",
            "item_name": "Ginger Tea (medium)",
            "item_tax_rate": "{\"Output Tax SGST - HFABPL\": 2.5, \"Output Tax CGST - HFABPL\": 2.5}",
            "item_tax_template": "GST 5% - HFABPL",
            "margin_rate_or_amount": 0,
            "margin_type": "",
            "name": "new-sales-invoice-item-uicnovjvho",
            "net_amount": 85.71,
            "net_rate": 85.71,
            "owner": "kunal.m@jcssglobal.com",
            "page_break": 0,
            "parent": "new-sales-invoice-bfbpkipkkt",
            "parentfield": "items",
            "parenttype": "Sales Invoice",
            "price_list_rate": 0,
            "qty": 1,
            "rate": 85.71,
            "rate_with_margin": 0,
            "sgst_amount": 0,
            "sgst_rate": 0,
            "stock_qty": 0,
            "stock_uom": "Nos",
            "stock_uom_rate": 0,
            "taxable_value": 85.71,
            "total_weight": 0,
            "uom": "Nos",
            "use_serial_batch_fields": 0,
            "warehouse": "BRIGADE ROAD - HK",
            "weight_per_unit": 0
        }
    ],
    "taxes": [
      {
        "name": "61945rmf0g",
        "owner": "kunal.m@jcssglobal.com",
        "creation": "2025-01-07 16:09:23.000433",
        "modified": "2025-01-07 16:09:23.000433",
        "modified_by": "kunal.m@jcssglobal.com",
        "docstatus": 0,
        "idx": 1,
        "charge_type": "On Net Total",
        "account_head": "Output Tax SGST - HFABPL",
        "description": "Output Tax SGST",
        "included_in_print_rate": 0,
        "included_in_paid_amount": 0,
        "cost_center": "Head Office - HFABPL",
        "rate": 0,
        "gst_tax_type": "sgst",
        "account_currency": "INR",
        "tax_amount": 92.14,
        "total": 5277.79,
        "tax_amount_after_discount_amount": 92.14,
        "base_tax_amount": 92.14,
        "base_total": 5277.79,
        "base_tax_amount_after_discount_amount": 92.14,
        "item_wise_tax_detail": null,
        "dont_recompute_tax": 0,
        "parent": "SINV-KL-00015",
        "parentfield": "taxes",
        "parenttype": "Sales Invoice",
        "doctype": "Sales Taxes and Charges"
      },
      {
        "name": "o2bh0hokp0",
        "owner": "kunal.m@jcssglobal.com",
        "creation": "2025-01-07 16:09:23.000433",
        "modified": "2025-01-07 16:09:23.000433",
        "modified_by": "kunal.m@jcssglobal.com",
        "docstatus": 0,
        "idx": 2,
        "charge_type": "On Net Total",
        "account_head": "Output Tax CGST - HFABPL",
        "description": "Output Tax CGST",
        "included_in_print_rate": 0,
        "included_in_paid_amount": 0,
        "cost_center": "Head Office - HFABPL",
        "rate": 0,
        "gst_tax_type": "cgst",
        "account_currency": "INR",
        "tax_amount": 92.14,
        "total": 5277.79,
        "tax_amount_after_discount_amount": 92.14,
        "base_tax_amount": 92.14,
        "base_total": 5277.79,
        "base_tax_amount_after_discount_amount": 92.14,
        "item_wise_tax_detail": null,
        "dont_recompute_tax": 0,
        "parent": "SINV-KL-00015",
        "parentfield": "taxes",
        "parenttype": "Sales Invoice",
        "doctype": "Sales Taxes and Charges"
      }
    ]
  }
  module.exports = test